### ISSUE TITLE
Plugin doesn't load

### ISSUE THREAD

**Issue by XOTlC** [Alex1304/ultimategdbot-gd-plugin#2]
Hello. Everytime I try to load the plugin I get this error

2020-01-11 15:45:55.137 [elastic-3] DEBUG discord4j.core.StateHolder - Using a ForwardingStore{forwardingTo=ShardAwareStore{valueStore=JdkStore@577b4b12{map=java.util.concurrent.ConcurrentHashMap}}} backend for channel storage.
2020-01-11 15:45:55.142 [elastic-3] DEBUG discord4j.core.StateHolder - Using a ForwardingStore{forwardingTo=ShardAwareStore{valueStore=JdkStore@21b38c7e{map=java.util.concurrent.ConcurrentHashMap}}} backend for guild storage.
2020-01-11 15:45:55.144 [elastic-3] DEBUG discord4j.core.StateHolder - Using a ForwardingStore{forwardingTo=ShardAwareStore{valueStore=JdkStore@2057da12{map=java.util.concurrent.ConcurrentHashMap}}} backend for guild emoji storage.
2020-01-11 15:45:55.145 [elastic-3] DEBUG discord4j.core.StateHolder - Using a ShardAwareStore{valueStore=JdkStore@46603b2f{map=java.util.concurrent.ConcurrentHashMap}} backend for member storage.
2020-01-11 15:45:55.189 [elastic-3] DEBUG discord4j.core.StateHolder - Using a ForwardingStore{forwardingTo=ShardAwareStore{valueStore=discord4j.store.caffeine.CaffeineStore@83191cd}} backend for message storage.
2020-01-11 15:45:55.191 [elastic-3] DEBUG discord4j.core.StateHolder - Using a ShardAwareStore{valueStore=JdkStore@6ff94844{map=java.util.concurrent.ConcurrentHashMap}} backend for presence storage.
2020-01-11 15:45:55.194 [elastic-3] DEBUG discord4j.core.StateHolder - Using a ForwardingStore{forwardingTo=ShardAwareStore{valueStore=JdkStore@508b7d39{map=java.util.concurrent.ConcurrentHashMap}}} backend for role storage.
2020-01-11 15:45:55.195 [elastic-3] DEBUG discord4j.core.StateHolder - Using a ForwardingStore{forwardingTo=ShardAwareStore{valueStore=JdkStore@448835c3{map=java.util.concurrent.ConcurrentHashMap}}} backend for user storage.
2020-01-11 15:45:55.196 [elastic-3] DEBUG discord4j.core.StateHolder - Using a ShardAwareStore{valueStore=JdkStore@43a5d434{map=java.util.concurrent.ConcurrentHashMap}} backend for voice state storage.
2020-01-11 15:45:55.220 [elastic-3] INFO  discord4j.core.DiscordClientBuilder - Shard 0 with Discord4J 3.0.12 (https://discord4j.com)
2020-01-11 15:45:55.266 [main] DEBUG discord4j.core.event.EventDispatcher - [5c00384f] ReadyEvent subscription created
2020-01-11 15:45:55.347 [main] INFO  ultimategdbot - Loaded plugin: Core
2020-01-11 15:45:55.347 [main] DEBUG ultimategdbot - Plugin Core is providing commands: CommandProvider{commandMap={help=AnnotatedCommand{obj=com.github.alex1304.ultimategdbot.core.HelpCommand@553f1d75}, settings=AnnotatedCommand{obj=com.github.alex1304.ultimategdbot.core.SetupCommand@6e1d8f9e}, system=AnnotatedCommand{obj=com.github.alex1304.ultimategdbot.core.SystemCommand@3e34ace1}, ping=AnnotatedCommand{obj=com.github.alex1304.ultimategdbot.core.PingCommand@62fe6067}, about=AnnotatedCommand{obj=com.github.alex1304.ultimategdbot.core.AboutCommand@4f071df8}, setup=AnnotatedCommand{obj=com.github.alex1304.ultimategdbot.core.SetupCommand@6e1d8f9e}, botadmins=AnnotatedCommand{obj=com.github.alex1304.ultimategdbot.core.BotAdminsCommand@4de41af9}, blacklist=AnnotatedCommand{obj=com.github.alex1304.ultimategdbot.core.BlacklistCommand@56ace400}, cacheinfo=AnnotatedCommand{obj=com.github.alex1304.ultimategdbot.core.CacheInfoCommand@47404bea}, configure=AnnotatedCommand{obj=com.github.alex1304.ultimategdbot.core.SetupCommand@6e1d8f9e}, manual=AnnotatedCommand{obj=com.github.alex1304.ultimategdbot.core.HelpCommand@553f1d75}, config=AnnotatedCommand{obj=com.github.alex1304.ultimategdbot.core.SetupCommand@6e1d8f9e}}, errorHandler=CommandErrorHandler{handledErrors=[com.github.alex1304.ultimategdbot.api.command.CommandFailedException, com.github.alex1304.ultimategdbot.api.command.PermissionDeniedException, discord4j.rest.http.client.ClientException, com.github.alex1304.ultimategdbot.api.DatabaseException]}}
2020-01-11 15:45:55.889 [reactor-http-nio-4] DEBUG jdash - Request sent: GDLoginRequest[path=/accounts/loginGJAccount.php, params={password=password, secret=Wmfv3899gc9, userName=TGDPSBOT, udid=jdash-client}]
2020-01-11 15:45:56.053 [jdash-client-forkjoin-2] ERROR ultimategdbot - Failed to load plugin Geometry Dash
java.lang.RuntimeException: Failed to login with the given Geometry Dash credentials
	at com.github.alex1304.ultimategdbot.gdplugin.GDPlugin.lambda$setup$2(GDPlugin.java:136)
	at reactor.core.publisher.Mono.lambda$onErrorMap$24(Mono.java:3076)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:350)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:350)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:100)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:350)
	at reactor.core.publisher.Operators.error(Operators.java:181)
	at reactor.core.publisher.MonoError.subscribe(MonoError.java:52)
	at reactor.core.publisher.MonoCallableOnAssembly.subscribe(MonoCallableOnAssembly.java:82)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3858)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:97)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:350)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:134)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:350)
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:114)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onError(FluxTimeout.java:212)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:350)
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:114)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:193)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:235)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:350)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:407)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:244)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:345)
	at reactor.core.publisher.FluxIndex$IndexSubscriber.onNext(FluxIndex.java:95)
	at reactor.core.publisher.DirectProcessor$DirectInner.onNext(DirectProcessor.java:333)
	at reactor.core.publisher.DirectProcessor.onNext(DirectProcessor.java:142)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:89)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:161)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:350)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:350)
	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:184)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoError] :
Error has been observed by the following operator(s):
	|_	[no operator assembly information]
	|_	Mono.onErrorMap ⇢ com.github.alex1304.ultimategdbot.gdplugin.GDPlugin.setup(GDPlugin.java:136)
	|_	Mono.doOnNext ⇢ com.github.alex1304.ultimategdbot.gdplugin.GDPlugin.setup(GDPlugin.java:137)
	|_	Mono.when ⇢ com.github.alex1304.ultimategdbot.gdplugin.GDPlugin.setup(GDPlugin.java:130)
	|_	Mono.then ⇢ com.github.alex1304.ultimategdbot.gdplugin.GDPlugin.setup(GDPlugin.java:143)
	|_	Mono.thenReturn ⇢ com.github.alex1304.ultimategdbot.api.Bot.lambda$start$9(Bot.java:381)

Caused by: com.github.alex1304.jdash.exception.GDLoginFailedException: 404 Not Found
	at reactor.core.publisher.Mono.lambda$onErrorMap$23(Mono.java:3062)
	at reactor.core.publisher.Mono.lambda$onErrorResume$25(Mono.java:3152)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
	... 28 common frames omitted
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoError] :
Error has been observed by the following operator(s):
	|_	[no operator assembly information]
	|_	Mono.onErrorMap ⇢ com.github.alex1304.jdash.client.GDClientBuilder.lambda$buildAuthenticated$1(GDClientBuilder.java:154)
	|_	Mono.flatMap ⇢ com.github.alex1304.jdash.client.GDClientBuilder.buildAuthenticated(GDClientBuilder.java:151)

Caused by: com.github.alex1304.jdash.exception.BadResponseException: null
	at com.github.alex1304.jdash.client.AbstractGDClient.lambda$fetch$3(AbstractGDClient.java:105)
	at reactor.netty.http.client.HttpClientFinalizer.lambda$responseSingle$7(HttpClientFinalizer.java:95)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:345)
	at reactor.core.publisher.FluxRetryPredicate$RetryPredicateSubscriber.onNext(FluxRetryPredicate.java:81)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:345)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:156)
	at reactor.netty.http.client.HttpClientConnect$HttpObserver.onStateChange(HttpClientConnect.java:405)
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:492)
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onStateChange(PooledConnectionProvider.java:503)
	at reactor.netty.resources.PooledConnectionProvider$PooledConnection.onStateChange(PooledConnectionProvider.java:442)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:520)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:89)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:313)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:427)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoError] :
	reactor.core.publisher.Mono.error(Mono.java:261)
	com.github.alex1304.jdash.client.AbstractGDClient.lambda$fetch$3(AbstractGDClient.java:105)
Error has been observed by the following operator(s):
	|_	Mono.error ⇢ com.github.alex1304.jdash.client.AbstractGDClient.lambda$fetch$3(AbstractGDClient.java:105)
	|_	Mono.doFinally ⇢ reactor.netty.http.client.HttpClientFinalizer.lambda$responseSingle$7(HttpClientFinalizer.java:97)
	|_	Mono.flatMap ⇢ reactor.netty.http.client.HttpClientFinalizer.responseSingle(HttpClientFinalizer.java:95)
	|_	Mono.publishOn ⇢ com.github.alex1304.jdash.client.AbstractGDClient.fetch(AbstractGDClient.java:110)
	|_	Mono.flatMap ⇢ com.github.alex1304.jdash.client.AbstractGDClient.fetch(AbstractGDClient.java:111)
	|_	Flux.concatMap ⇢ reactor.retry.DefaultRetry.apply(DefaultRetry.java:115)
	|_	Mono.retryWhen ⇢ com.github.alex1304.jdash.client.AbstractGDClient.fetch(AbstractGDClient.java:130)
	|_	Mono.timeout ⇢ com.github.alex1304.jdash.client.AbstractGDClient.fetch(AbstractGDClient.java:138)
	|_	Mono.map ⇢ com.github.alex1304.jdash.client.GDClientBuilder.lambda$buildAuthenticated$1(GDClientBuilder.java:152)

2020-01-11 15:45:57.548 [main] ERROR c.g.alex1304.ultimategdbot.core.Main - The bot could not be started. Make sure that all configuration files are present and have a valid content
java.lang.RuntimeException: Failed to login with the given Geometry Dash credentials
	at com.github.alex1304.ultimategdbot.gdplugin.GDPlugin.lambda$setup$2(GDPlugin.java:136)
	at reactor.core.publisher.Mono.lambda$onErrorMap$24(Mono.java:3076)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:350)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:350)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:100)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:350)
	at reactor.core.publisher.Operators.error(Operators.java:181)
	at reactor.core.publisher.MonoError.subscribe(MonoError.java:52)
	at reactor.core.publisher.MonoCallableOnAssembly.subscribe(MonoCallableOnAssembly.java:82)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3858)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:97)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:350)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:134)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:350)
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:114)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onError(FluxTimeout.java:212)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:350)
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:114)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.whenError(FluxRetryWhen.java:193)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onError(FluxRetryWhen.java:235)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:350)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:407)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:244)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:345)
	at reactor.core.publisher.FluxIndex$IndexSubscriber.onNext(FluxIndex.java:95)
	at reactor.core.publisher.DirectProcessor$DirectInner.onNext(DirectProcessor.java:333)
	at reactor.core.publisher.DirectProcessor.onNext(DirectProcessor.java:142)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:89)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onError(FluxRetryWhen.java:161)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:350)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:350)
	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:184)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoError] :
Error has been observed by the following operator(s):
	|_	[no operator assembly information]
	|_	Mono.onErrorMap ⇢ com.github.alex1304.ultimategdbot.gdplugin.GDPlugin.setup(GDPlugin.java:136)
	|_	Mono.doOnNext ⇢ com.github.alex1304.ultimategdbot.gdplugin.GDPlugin.setup(GDPlugin.java:137)
	|_	Mono.when ⇢ com.github.alex1304.ultimategdbot.gdplugin.GDPlugin.setup(GDPlugin.java:130)
	|_	Mono.then ⇢ com.github.alex1304.ultimategdbot.gdplugin.GDPlugin.setup(GDPlugin.java:143)
	|_	Mono.thenReturn ⇢ com.github.alex1304.ultimategdbot.api.Bot.lambda$start$9(Bot.java:381)
	|_	Mono.doOnError ⇢ com.github.alex1304.ultimategdbot.api.Bot.lambda$start$9(Bot.java:382)
	|_	Flux.flatMap ⇢ com.github.alex1304.ultimategdbot.api.Bot.start(Bot.java:381)
	|_	Flux.doOnNext ⇢ com.github.alex1304.ultimategdbot.api.Bot.start(Bot.java:383)
	|_	Flux.doOnNext ⇢ com.github.alex1304.ultimategdbot.api.Bot.start(Bot.java:384)
	|_	Flux.doOnNext ⇢ com.github.alex1304.ultimategdbot.api.Bot.start(Bot.java:385)
	|_	Flux.doOnNext ⇢ com.github.alex1304.ultimategdbot.api.Bot.start(Bot.java:386)
	|_	Flux.doOnNext ⇢ com.github.alex1304.ultimategdbot.api.Bot.start(Bot.java:387)
	|_	Flux.then ⇢ com.github.alex1304.ultimategdbot.api.Bot.start(Bot.java:388)
	|_	Mono.then ⇢ com.github.alex1304.ultimategdbot.api.Bot.start(Bot.java:389)
	|_	Mono.then ⇢ com.github.alex1304.ultimategdbot.api.Bot.start(Bot.java:393)

	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
		at reactor.core.publisher.Mono.block(Mono.java:1494)
		at com.github.alex1304.ultimategdbot.core.Main.main(Main.java:29)
Caused by: com.github.alex1304.jdash.exception.GDLoginFailedException: 404 Not Found
	at reactor.core.publisher.Mono.lambda$onErrorMap$23(Mono.java:3062)
	at reactor.core.publisher.Mono.lambda$onErrorResume$25(Mono.java:3152)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
	... 28 common frames omitted
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoError] :
Error has been observed by the following operator(s):
	|_	[no operator assembly information]
	|_	Mono.onErrorMap ⇢ com.github.alex1304.jdash.client.GDClientBuilder.lambda$buildAuthenticated$1(GDClientBuilder.java:154)
	|_	Mono.flatMap ⇢ com.github.alex1304.jdash.client.GDClientBuilder.buildAuthenticated(GDClientBuilder.java:151)

Caused by: com.github.alex1304.jdash.exception.BadResponseException: null
	at com.github.alex1304.jdash.client.AbstractGDClient.lambda$fetch$3(AbstractGDClient.java:105)
	at reactor.netty.http.client.HttpClientFinalizer.lambda$responseSingle$7(HttpClientFinalizer.java:95)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:345)
	at reactor.core.publisher.FluxRetryPredicate$RetryPredicateSubscriber.onNext(FluxRetryPredicate.java:81)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onNext(FluxOnAssembly.java:345)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:156)
	at reactor.netty.http.client.HttpClientConnect$HttpObserver.onStateChange(HttpClientConnect.java:405)
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:492)
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onStateChange(PooledConnectionProvider.java:503)
	at reactor.netty.resources.PooledConnectionProvider$PooledConnection.onStateChange(PooledConnectionProvider.java:442)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:520)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:89)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:313)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:427)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoError] :
	reactor.core.publisher.Mono.error(Mono.java:261)
	com.github.alex1304.jdash.client.AbstractGDClient.lambda$fetch$3(AbstractGDClient.java:105)
Error has been observed by the following operator(s):
	|_	Mono.error ⇢ com.github.alex1304.jdash.client.AbstractGDClient.lambda$fetch$3(AbstractGDClient.java:105)
	|_	Mono.doFinally ⇢ reactor.netty.http.client.HttpClientFinalizer.lambda$responseSingle$7(HttpClientFinalizer.java:97)
	|_	Mono.flatMap ⇢ reactor.netty.http.client.HttpClientFinalizer.responseSingle(HttpClientFinalizer.java:95)
	|_	Mono.publishOn ⇢ com.github.alex1304.jdash.client.AbstractGDClient.fetch(AbstractGDClient.java:110)
	|_	Mono.flatMap ⇢ com.github.alex1304.jdash.client.AbstractGDClient.fetch(AbstractGDClient.java:111)
	|_	Flux.concatMap ⇢ reactor.retry.DefaultRetry.apply(DefaultRetry.java:115)
	|_	Mono.retryWhen ⇢ com.github.alex1304.jdash.client.AbstractGDClient.fetch(AbstractGDClient.java:130)
	|_	Mono.timeout ⇢ com.github.alex1304.jdash.client.AbstractGDClient.fetch(AbstractGDClient.java:138)
	|_	Mono.map ⇢ com.github.alex1304.jdash.client.GDClientBuilder.lambda$buildAuthenticated$1(GDClientBuilder.java:152)

**Comment by Alex1304** [comment]
The bot gets a 404 Not Found error when trying to login to the GD account. This means that `gdplugin.host` in `plugins.properties` is incorrect. Double check that

**Comment by XOTlC** [comment]
okay thanks!

**Comment by XOTlC** [comment]
also btw does it have to include /database after?
